// src/app/features/todos/pages/todo-list/todo-list.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  OnInit,
  computed,
  effect,
  inject,
  output,
  signal,
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import { toSignal } from '@angular/core/rxjs-interop';
import { Store } from '@ngrx/store';
import { Todo } from '@app/features/todos/data-access/todo.model';
import * as TodoActions from '@app/features/todos/data-access/todo.actions';
import * as TodoSelectors from '@app/features/todos/data-access/todo.selectors';
import { SpinnerComponent } from '@app/shared/ui/spinner/spinner.component';
import { TodoItemComponent } from '@app/features/todos/ui/todo-item/todo-item.component';
import { TodoStatsPanelComponent } from '@app/features/todos/ui/todo-stats-panel/todo-stats-panel.component';
import { ToastService } from '@app/shared/ui/toast/toast.service';

type TodoFilter = 'all' | 'active' | 'done';

@Component({
  selector: 'app-todo-list',
  standalone: true,
  imports: [FormsModule, SpinnerComponent, TodoItemComponent, TodoStatsPanelComponent],
  templateUrl: './todo-list.component.html',
  styleUrls: ['./todo-list.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TodoListComponent implements OnInit {
  private readonly store = inject(Store);
  private readonly toast = inject(ToastService);

  readonly todos = toSignal(this.store.select(TodoSelectors.selectAllTodos), {
    initialValue: [] as Todo[],
  });
  readonly loading = toSignal(this.store.select(TodoSelectors.selectTodosLoading), {
    initialValue: false,
  });
  readonly error = toSignal(this.store.select(TodoSelectors.selectTodosError), {
    initialValue: null,
  });
  readonly filter = signal<TodoFilter>('all');
  readonly filteredTodos = computed(() => {
    const items = this.todos();
    const f = this.filter();

    switch (f) {
      case 'active':
        return items.filter((todo) => !todo.completed);
      case 'done':
        return items.filter((todo) => todo.completed);
      default:
        return items;
    }
  });
  readonly todoToggled = output<string>();

  newTask = '';
  editingTodo: Todo | null = null;
  updatedTask = '';

  constructor() {
    effect(() => {
      const err = this.error();
      if (err) {
        this.toast.error(err);
      }
    });
  }

  ngOnInit(): void {
    this.store.dispatch(TodoActions.loadTodos());
  }

  addTodo(): void {
    if (!this.newTask.trim()) return;
    const task = this.newTask.trim();
    this.store.dispatch(TodoActions.addTodo({ task }));
    this.newTask = '';
  }

  setFilter(value: TodoFilter): void {
    this.filter.set(value);
  }

  onTodoToggled(todoId: string): void {
    if (this.loading()) return;

    const todo = this.todos().find((item) => item.id === todoId);
    if (!todo) return;

    const updatedTodo = { ...todo, completed: !todo.completed };
    this.store.dispatch(TodoActions.updateTodo({ todo: updatedTodo }));
    this.todoToggled.emit(todoId);
  }

  deleteTodo(todoId: string): void {
    if (this.loading()) return;
    if (confirm('Are you sure you want to delete this task?')) {
      this.store.dispatch(TodoActions.deleteTodo({ todoId }));
    }
  }

  startEdit(todo: Todo): void {
    if (this.loading()) return;
    this.editingTodo = { ...todo };
    this.updatedTask = todo.task;
  }

  cancelEdit(): void {
    this.editingTodo = null;
    this.updatedTask = '';
  }

  saveEdit(): void {
    if (this.loading()) return;
    if (this.editingTodo && this.updatedTask.trim()) {
      const todoToUpdate = {
        ...this.editingTodo,
        task: this.updatedTask.trim(),
      };
      this.store.dispatch(TodoActions.updateTodo({ todo: todoToUpdate }));
      this.cancelEdit();
    }
  }

}

<div class="todo-list-container">
  <form (ngSubmit)="addTodo()" class="add-todo-form">
    <input
      type="text"
      [(ngModel)]="newTask"
      name="newTask"
      placeholder="What needs to be done?"
      required
      [disabled]="loading()"
    />
    <button type="submit" [disabled]="!newTask.trim()">
      Add Task
    </button>
  </form>

  @if (loading()) {
    <div class="todo-loading" aria-busy="true">
      <app-spinner />
      <span>Loading tasks…</span>
    </div>
  } @else if (error(); as err) {
    <div class="error-message">{{ err }}</div>
  } @else {
    @defer (on viewport) {
      <app-todo-stats-panel [todos]="todos()" />
    } @placeholder {
      <div class="skeleton"></div>
    }

    <div class="filter-bar" role="group" aria-label="Filter tasks">
      <button
        type="button"
        class="filter-btn"
        [class.active]="filter() === 'all'"
        (click)="setFilter('all')"
      >
        All
      </button>
      <button
        type="button"
        class="filter-btn"
        [class.active]="filter() === 'active'"
        (click)="setFilter('active')"
      >
        Active
      </button>
      <button
        type="button"
        class="filter-btn"
        [class.active]="filter() === 'done'"
        (click)="setFilter('done')"
      >
        Done
      </button>
    </div>

    @let count = filteredTodos().length;
    <span class="todo-count">{{ count }} items</span>

    <ul>
      @for (todo of filteredTodos(); track todo.id) {
        <li [class.completed]="todo.completed">
          @if (editingTodo?.id !== todo.id) {
            <app-todo-item
              [todo]="todo"
              [disabled]="loading()"
              (toggled)="onTodoToggled(todo.id)"
            >
              <button
                type="button"
                (click)="startEdit(todo)"
                class="edit-btn"
                [disabled]="loading()"
              >
                Edit
              </button>
              <button
                type="button"
                (click)="deleteTodo(todo.id)"
                class="delete-btn"
                [disabled]="loading()"
              >
                Delete
              </button>
            </app-todo-item>
          } @else {
            <div class="edit-mode">
              <input
                type="text"
                [(ngModel)]="updatedTask"
                name="updatedTask"
                class="edit-input"
                (keyup.enter)="saveEdit()"
                (keyup.escape)="cancelEdit()"
                [disabled]="loading()"
              />
              <div class="actions">
                <button
                  type="button"
                  (click)="saveEdit()"
                  class="save-btn"
                  [disabled]="loading()"
                >
                  Save
                </button>
                <button
                  type="button"
                  (click)="cancelEdit()"
                  class="cancel-btn"
                  [disabled]="loading()"
                >
                  Cancel
                </button>
              </div>
            </div>
          }
        </li>
      } @empty {
        <li class="empty-list-message">No todos</li>
      }
    </ul>
  }
</div>

// apps/marketing-mfe/src/features/todos/TodoList.tsx
import {
  FormEvent,
  useCallback,
  useEffect,
  useMemo,
  useState,
} from 'react';
import {
  createTodo,
  deleteTodo,
  fetchTodos,
  updateTodo,
  type Todo,
} from '@marketing/core/api';
import { Toast } from '@marketing/shared/ui/toast';
import { applyFilter, type TodoFilter } from './apply-filter';
import './TodoList.css';

interface TodoListProps {
  userId: string;
  accessToken: string;
  userName: string;
  onLogout: () => void;
}

export function TodoList({
  userId,
  accessToken,
  userName,
  onLogout,
}: TodoListProps) {
  const [todos, setTodos] = useState<Todo[]>([]);
  const [filter, setFilter] = useState<TodoFilter>('all');
  const [newTask, setNewTask] = useState('');
  const [loading, setLoading] = useState(true);
  const [mutating, setMutating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    async function loadTodos() {
      setLoading(true);
      setError(null);

      try {
        const items = await fetchTodos(userId, accessToken);
        if (!cancelled) {
          setTodos(items);
        }
      } catch (err) {
        if (!cancelled) {
          const message =
            err instanceof Error ? err.message : 'Failed to load todos';
          setError(message);
        }
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    }

    void loadTodos();

    return () => {
      cancelled = true;
    };
  }, [userId, accessToken]);

  const filtered = useMemo(
    () => applyFilter(todos, filter),
    [todos, filter]
  );

  const runMutation = useCallback(
    async (action: () => Promise<void>) => {
      setMutating(true);
      setError(null);

      try {
        await action();
      } catch (err) {
        const message =
          err instanceof Error ? err.message : 'Todo action failed';
        setError(message);
      } finally {
        setMutating(false);
      }
    },
    []
  );

  async function handleAdd(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const task = newTask.trim();
    if (!task || mutating) {
      return;
    }

    await runMutation(async () => {
      const created = await createTodo(task, userId, accessToken);
      setTodos((current) => [...current, created]);
      setNewTask('');
    });
  }

  async function handleToggle(todo: Todo) {
    if (mutating) {
      return;
    }

    await runMutation(async () => {
      const updated = await updateTodo(
        { id: todo.id, completed: !todo.completed },
        userId,
        accessToken
      );
      setTodos((current) =>
        current.map((item) => (item.id === updated.id ? updated : item))
      );
    });
  }

  async function handleDelete(todoId: string) {
    if (mutating) {
      return;
    }

    if (!window.confirm('Are you sure you want to delete this task?')) {
      return;
    }

    await runMutation(async () => {
      await deleteTodo(todoId, userId, accessToken);
      setTodos((current) => current.filter((item) => item.id !== todoId));
    });
  }

  return (
    <main className="todo-page">
      <header className="todo-header">
        <div>
          <p className="todo-header__eyebrow">marketing-mfe</p>
          <h1>My Todos</h1>
          <p className="todo-header__user">Signed in as {userName}</p>
        </div>
        <button type="button" className="todo-header__logout" onClick={onLogout}>
          Logout
        </button>
      </header>

      {error ? (
        <Toast type="error" message={error} onDismiss={() => setError(null)} />
      ) : null}

      <section className="todo-card">
        <form className="todo-form" onSubmit={handleAdd}>
          <input
            type="text"
            value={newTask}
            onChange={(event) => setNewTask(event.target.value)}
            placeholder="What needs to be done?"
            disabled={loading || mutating}
            aria-label="New task"
          />
          <button type="submit" disabled={!newTask.trim() || loading || mutating}>
            Add Task
          </button>
        </form>

        {loading ? (
          <p className="todo-status" aria-busy="true">
            Loading tasks…
          </p>
        ) : (
          <>
            <div className="todo-filters" role="group" aria-label="Filter tasks">
              {(['all', 'active', 'done'] as const).map((value) => (
                <button
                  key={value}
                  type="button"
                  className={
                    filter === value ? 'todo-filter todo-filter--active' : 'todo-filter'
                  }
                  onClick={() => setFilter(value)}
                >
                  {value.charAt(0).toUpperCase() + value.slice(1)}
                </button>
              ))}
            </div>

            <p className="todo-count">{filtered.length} items</p>

            <ul className="todo-list">
              {filtered.map((todo) => (
                <li
                  key={todo.id}
                  className={todo.completed ? 'todo-item todo-item--done' : 'todo-item'}
                >
                  <label className="todo-item__label">
                    <input
                      type="checkbox"
                      checked={todo.completed}
                      onChange={() => void handleToggle(todo)}
                      disabled={mutating}
                    />
                    <span>{todo.task}</span>
                  </label>
                  <button
                    type="button"
                    className="todo-item__delete"
                    onClick={() => void handleDelete(todo.id)}
                    disabled={mutating}
                  >
                    Delete
                  </button>
                </li>
              ))}
              {filtered.length === 0 ? (
                <li className="todo-empty">No todos</li>
              ) : null}
            </ul>
          </>
        )}
      </section>
    </main>
  );
}
